name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            output_name: MPV-Playlist-Player-Pro.exe
            artifact_name: windows-build
          - os: ubuntu-latest
            output_name: MPV-Playlist-Player-Pro.bin
            artifact_name: linux-build
          - os: macos-latest
            output_name: MPV-Playlist-Player-Pro.app
            artifact_name: macos-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install system dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y patchelf ccache

      - name: Install dependencies with uv
        run: |
          uv sync

      - name: Build with Nuitka (Windows)
        if: runner.os == 'Windows'
        timeout-minutes: 45
        run: |
          echo "Starting Nuitka compilation for Windows..."
          uv run nuitka --onefile --windows-console-mode=disable --enable-plugin=tk-inter --nofollow-import-to=customtkinter,ttkbootstrap --assume-yes-for-downloads main.py
          echo "Nuitka compilation completed"

      - name: Build with Nuitka (Linux)
        if: runner.os == 'Linux'
        timeout-minutes: 45
        run: |
          echo "Starting Nuitka compilation for Linux..."
          uv run nuitka --onefile --enable-plugin=tk-inter --nofollow-import-to=customtkinter,ttkbootstrap --assume-yes-for-downloads main.py
          echo "Nuitka compilation completed"

      - name: Build with Nuitka (macOS)
        if: runner.os == 'macOS'
        timeout-minutes: 45
        run: |
          echo "Starting Nuitka compilation for macOS..."
          uv run nuitka --standalone --macos-create-app-bundle --enable-plugin=tk-inter --nofollow-import-to=customtkinter,ttkbootstrap --macos-app-name="MPV Playlist Player Pro" --assume-yes-for-downloads main.py
          echo "Nuitka compilation completed"

      - name: List directory contents (Debug)
        shell: bash
        run: |
          echo "=== Root directory files ==="
          ls -lah
          echo ""
          echo "=== Looking for build artifacts ==="
          find . -maxdepth 2 -name "*.exe" -o -name "*.bin" -o -name "*.app" 2>/dev/null || true

      - name: Collect and rename artifacts
        shell: bash
        run: |
          mkdir -p dist

          if [ "${{ runner.os }}" == "macOS" ]; then
            echo "Processing macOS app bundle..."
            if [ -d "main.app" ]; then
              echo "✅ Found main.app in root"
              cp -r main.app dist/
              cd dist && zip -r ${{ matrix.output_name }}.zip main.app && rm -rf main.app && cd ..
            elif [ -d "main.dist/main.app" ]; then
              echo "✅ Found main.app in main.dist/"
              cp -r main.dist/main.app dist/
              cd dist && zip -r ${{ matrix.output_name }}.zip main.app && rm -rf main.app && cd ..
            else
              echo "❌ main.app not found"
              exit 1
            fi
          elif [ "${{ runner.os }}" == "Windows" ]; then
            echo "Processing Windows executable..."
            if [ -f "main.exe" ]; then
              echo "✅ Found main.exe in root directory"
              cp main.exe dist/${{ matrix.output_name }}
            else
              echo "❌ main.exe not found"
              exit 1
            fi
          else
            echo "Processing Linux binary..."
            if [ -f "main.bin" ]; then
              echo "✅ Found main.bin in root directory"
              cp main.bin dist/${{ matrix.output_name }}
              chmod +x dist/${{ matrix.output_name }}
            else
              echo "❌ main.bin not found"
              exit 1
            fi
          fi

          echo ""
          echo "=== Final dist/ contents ==="
          ls -lah dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/*
          if-no-files-found: error
          retention-days: 7

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display artifact structure
        run: ls -R artifacts

      - name: Prepare release files
        run: |
          mkdir -p release-files
          find artifacts -type f -exec cp {} release-files/ \;
          ls -lah release-files/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-files/*
          draft: false
          prerelease: false
          generate_release_notes: true
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
