name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            output_name: MPV-Playlist-Player-Pro.exe
            artifact_name: windows-build
          - os: ubuntu-latest
            output_name: MPV-Playlist-Player-Pro.bin
            artifact_name: linux-build
          - os: macos-latest
            output_name: MPV-Playlist-Player-Pro.app
            artifact_name: macos-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies with uv
        run: |
          uv sync

      - name: Build with Nuitka (Windows)
        if: runner.os == 'Windows'
        timeout-minutes: 45
        run: |
          uv run nuitka --onefile --windows-console-mode=disable --enable-plugin=tk-inter --include-package-data=customtkinter --include-package-data=ttkbootstrap --output-dir=build --output-filename=main.exe main.py

      - name: Build with Nuitka (Linux)
        if: runner.os == 'Linux'
        timeout-minutes: 45
        run: |
          uv run nuitka --onefile --enable-plugin=tk-inter --include-package-data=customtkinter --include-package-data=ttkbootstrap --output-dir=build --output-filename=main.bin main.py

      - name: Build with Nuitka (macOS)
        if: runner.os == 'macOS'
        timeout-minutes: 45
        run: |
          uv run nuitka --standalone --macos-create-app-bundle --enable-plugin=tk-inter --include-package-data=customtkinter --include-package-data=ttkbootstrap --output-dir=build --macos-app-name="MPV Playlist Player Pro" main.py

      - name: List build directory contents
        shell: bash
        run: |
          echo "=== Current directory ==="
          ls -la
          echo "=== Build directory ==="
          if [ -d "build" ]; then
            ls -laR build/
          else
            echo "Build directory does not exist"
          fi

      - name: Locate and verify build artifact
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "macOS" ]; then
            if [ -d "build/main.app" ]; then
              echo "✅ macOS app bundle found: build/main.app"
            else
              echo "❌ Build failed - build/main.app not found"
              exit 1
            fi
          elif [ "${{ runner.os }}" == "Windows" ]; then
            if [ -f "build/main.exe" ]; then
              echo "✅ Windows executable found: build/main.exe"
            else
              echo "❌ Build failed - build/main.exe not found"
              exit 1
            fi
          else
            if [ -f "build/main.bin" ]; then
              echo "✅ Linux binary found: build/main.bin"
            elif [ -f "main.bin" ]; then
              echo "⚠️ Linux binary found in root directory, moving to build/"
              mkdir -p build
              mv main.bin build/main.bin
            else
              echo "❌ Build failed - main.bin not found"
              exit 1
            fi
          fi

      - name: Make binary executable (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "macOS" ]; then
            chmod +x build/main.app/Contents/MacOS/* || true
          else
            chmod +x build/main.bin
          fi

      - name: Package artifacts
        shell: bash
        run: |
          mkdir -p dist
          if [ "${{ runner.os }}" == "macOS" ]; then
            cd build
            zip -r ../dist/${{ matrix.output_name }}.zip main.app
            cd ..
          elif [ "${{ runner.os }}" == "Windows" ]; then
            cp build/main.exe dist/${{ matrix.output_name }}
          else
            cp build/main.bin dist/${{ matrix.output_name }}
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/*
          if-no-files-found: error
          retention-days: 7

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Display artifact structure
        run: ls -R artifacts

      - name: Prepare release files
        run: |
          mkdir -p release-files
          find artifacts -type f -exec cp {} release-files/ \;
          ls -lah release-files/

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-files/*
          draft: false
          prerelease: false
          generate_release_notes: true
          fail_on_unmatched_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
